name: pep/carousel
typeName: pep_carousel
group: pep
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: image
    type: File
    allowed: common-image-types
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          landscape:
            title: Landscape
            value: 4 / 3
      landscape:
        title: Landscape
        allowedAspectRatios:
          landscape:
            title: landscape
            value: 2.4
      portrait:
        title: Portrait
        allowedAspectRatios:
          portrait:
            title: Portrait
            value: 0.5625