styles:
    templates:
        layoutRootPath: EXT:pep/Resources/Private/ContentElements/Layouts
        partialRootPath: EXT:pep/Resources/Private/ContentElements/Partials
        templateRootPath: EXT:pep/Resources/Private/ContentElements/Templates
    content:
        textmedia:
            maxW: 1200
            maxWInText: 600
            linkWrap:
                lightboxEnabled: true
                lightboxCssClass: lightbox
