categories:
  Pep:
    label: 'pep'
  Pep.templates:
    label: 'Templates'
    parent: Pep
  Pep.layout:
    label: 'Layout'
    parent: Pep
  Pep.menus:
    label: 'Menus'
    parent: Pep

settings:
  Pep.template_path:
    label: 'Page template path'
    category: Pep.templates
    description: 'Path to the templates of the pep.'
    type: string
    default: 'EXT:pep/Resources/Private/Templates/'

  Pep.logo:
    label: 'Logo'
    category: Pep.layout
    description: 'Path to the logo of pep.'
    type: string
    default: 'EXT:pep/Resources/Public/Images/logo.svg'

  Pep.logo-alt:
    label: 'Logo Alt text'
    category: Pep.layout
    description: 'Alternative text of the logo for the visually impaired'
    type: string
    default: 'Logo'

  Pep.favicon:
    label: 'Favicon'
    description: 'This icon is displayed in search engine results and in the browser tab'
    category: Pep.layout
    type: string
    default: 'EXT:pep/Resources/Public/Icons/favicon.ico'

  Pep.footerMenuRoot:
      label: 'Footer menu root uid'
      description: 'The subpages of this page are displayed in the footer'
      category: Pep.menus
      type: int
      default: 2
