name: pep/simpleteaser
typeName: pep_simpleteaser
group: pep
title: Simple Teaser
description: A simple teaser element with title, subtitle, image, and link.
iconIdentifier: content-simpleteaser
supertype: content
prefixFields: true
prefixType: full

fields:
  - identifier: header
    useExistingField: true

  - identifier: subheader
    type: Text
    required: false

  - identifier: bodytext
    useExistingField: true
    enableRichtext: true

  - identifier: media
    type: File
    allowedFileExtensions: jpg, jpeg, png, gif, webp
    maxItems: 1
    required: false

  - identifier: link
    type: Link
    required: false

template:
  templateName: SimpleTeaser
  layoutRootPaths:
    - 'EXT:pep/Resources/Private/Layouts/ContentBlocks/'
  templateRootPaths:
    - 'EXT:pep/ContentBlocks/ContentElements/SimpleTeaser/Templates/'
  partialRootPaths:
    - 'EXT:pep/Resources/Private/Partials/ContentBlocks/'
  templatePathAndFilename: 
    - 'EXT:pep/ContentBlocks/ContentElements/SimpleTeaser/Templates/SimpleTeaser.html'