name: pep/gradiemtteaser
typeName: pep_gradiemtteaser
group: pep
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: bodytext
    useExistingField: true
    enableRichtext: true
  -
    identifier: button_text
    type: Text
    default: 'Read more'
    min: 4
    max: 15
  -
    identifier: button_link
    type: Link
    required: true    
  - 
    identifier: bg_color
    type: Color
    autocomplete: true
    default: '#0000FF'
  - 
    identifier: text_color
    type: Color
    autocomplete: true
    default: '#0000FF'    
  - 
    identifier: select
    type: Select
    renderType: selectSingle
    items:
      - label: 'left'
        value: left
      - label: 'right'
        value: right    
  - 
    identifier: toggle
    type: Checkbox
    renderType: checkboxToggle
    default: 1
  -
    identifier: image
    type: File
    extendedPalette: false
    minitems: 1
    maxitems: 10
    allowed: common-image-types